### ISSUE TITLE
EOF while decoding the driver config upon RecoverTask

### ISSUE THREAD

**Issue by Kooper** [hashicorp/nomad-skeleton-driver-plugin#15] opened 2022-06-15 10:45 UTC
Hello,

I'm experimenting with the custom task driver following the project's README and recommendations from [Task Drivers](https://www.nomadproject.io/docs/internals/plugins/task-drivers). However, when using vanilla source of the skeleton project, I'm getting "failed to decode driver config: EOF" error upon task recover at [hello/driver.go#L437](https://github.com/hashicorp/nomad-skeleton-driver-plugin/blob/main/hello/driver.go#L437)

```go
var driverConfig TaskConfig
if err := taskState.TaskConfig.DecodeDriverConfig(&driverConfig); err != nil {
	return fmt.Errorf("failed to decode driver config: %v", err)
}
```

Steps to reproduce:
1. Compile the project, enable the driver in the nomad client configuration according to the instructions, restart nomad client.
2. Create the job using configuration from the examples folder.
3. Restart nomad client.

Actual result:
1. RecoverTask is called for completed and running allocations, and always returns with the error
2. Handle passed to RecoverTask always contains a kind of incomplete driver state. F.e. rawDriverConfig and NodeID (fields I had plan to rely for reasoning about local task status) are empty
3. Handle passed to RecoverTask contains State = "unknown", even for completed allocations.

Expected result:
1. Driver-specific logic could be called, with the dependency to NodeID and known state of the allocation.

Additional details:
I have 3-nodes cluster, 1 server and 2 clients, using Vagrant environment from https://github.com/egmanoj/hashilab.git

**Comment by angrycub** [comment] 2023-05-23 21:24
I took some time today to test this issue against the current state of main and I am unable to reproduce it.  There have been some significant dependency updates over the gap between now and when it was last handled. I am going to go ahead and close this issue. If it can be reproduced in the future, it's probably best to start with a fresh issue report at this point.

**Closed by angrycub** 2023-05-23 21:24 UTC
Labels: bug
